[package]
name = "ckb-db"
version = "0.33.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
ckb-app-config = { path = "../util/app-config" }
ckb-logger = { path = "../util/logger" }
ckb-error = { path = "../error" }
tempfile = "3.0"
libc = "0.2"
rocksdb = { package = "ckb-rocksdb", git = "https://github.com/nervosnetwork/rust-rocksdb", branch = "delete_file_in_range", features = ["snappy"] }
